version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASS}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ROOT_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=${ADMIN_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ADMIN_PASS}
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
